apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-pod
    service: webserver
  name: my-pod
spec:
  containers:
  - image: nginx
    name: my-pod-nginx
    resources: {}
  - image: alpine
    name: alpine-pod
    args:
    - sleep
    - "1800"
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
